/*
 * This file is part of the open source LUKKEY project.
 * Licensed under the MIT License. See LICENSE for details.
 * © Copyright LUKKEY AG
 */
import { RUNTIME_DEV } from "../utils/runtimeFlags";
import {
  getAssetChainShortName,
  getAssetChainFullName,
  getAssetDisplayName,
  getAssetSymbol,
  getAssetType,
} from "./assetFields";

export {
  getAssetChainShortName,
  getAssetChainFullName,
  getAssetDisplayName,
  getAssetSymbol,
  getAssetType,
} from "./assetFields";

const hiddenInDevelopmentChainNames = new Set([
  "celestia",
  "gnosis",
  "juno",
  "linea",
]);

const removedAssetKeys = new Set(["tron:usdc", "zksync:zksync"]);
const assetConfigOverrides = {
  "zksync:eth": {
    type: "native",
    contractAddress: "",
  },
};

const getAssetKey = (asset) =>
  `${String(asset?.chainFullName || asset?.queryChainName || "")
    .trim()
    .toLowerCase()}:${String(getAssetSymbol(asset) || "")
    .trim()
    .toLowerCase()}`;

export const normalizeAssetConfig = (asset) => {
  const {
    name,
    displayName,
    symbol,
    type,
    Decimals,
    decimals,
    chainFullName,
    contractAddress,
    queryChainName,
    queryChainShortName,
    shortName,
    coin_type,
    fee,
    ...rest
  } = asset || {};
  return {
    name: getAssetDisplayName(asset),
    symbol: getAssetSymbol(asset),
    type: getAssetType(asset),
    ...(Decimals != null ? { Decimals } : {}),
    ...(decimals != null ? { decimals } : {}),
    chainFullName: getAssetChainFullName(asset),
    ...(contractAddress !== undefined ? { contractAddress } : {}),
    ...rest,
    fee: fee ?? "",
    ...(assetConfigOverrides[getAssetKey(asset)] || {}),
  };
};

const configuredInitialAdditionalCryptos = [
  {
    name: "Arbitrum",
    symbol: "ARB",
    type: "erc20",
    Decimals: "18",
    chainFullName: "arbitrum",
    contractAddress: "0x912CE59144191C1204E64559FE8253a0e49E6548",
  },
  {
    name: "Ethereum",
    symbol: "ARETH",
    type: "native",
    Decimals: "18",
    chainFullName: "arbitrum",
    contractAddress: "",
  },
  {
    name: "Dai",
    symbol: "DAI",
    type: "erc20",
    Decimals: "18",
    chainFullName: "arbitrum",
    contractAddress: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1",
  },
  {
    name: "Tether USD",
    symbol: "USDT",
    type: "erc20",
    Decimals: "6",
    chainFullName: "arbitrum",
    contractAddress: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9",
  },
  {
    name: "USDC",
    symbol: "USDC",
    type: "erc20",
    Decimals: "6",
    chainFullName: "arbitrum",
    contractAddress: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
  },
  {
    name: "Bridged USDC",
    symbol: "USDC.e",
    type: "erc20",
    Decimals: "6",
    chainFullName: "arbitrum",
    contractAddress: "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8",
  },
  {
    name: "Ethereum",
    symbol: "ETH",
    type: "native",
    Decimals: "18",
    chainFullName: "aurora",
    contractAddress: "",
  },
  {
    name: "Aurora",
    symbol: "AURORA",
    type: "erc20",
    Decimals: "18",
    chainFullName: "aurora",
    contractAddress: "0x8BEc47865aDe3B172A928df8f990Bc7f2A3b9f79",
  },
  {
    name: "DOVU",
    symbol: "DOVU",
    type: "erc20",
    Decimals: "8",
    chainFullName: "aurora",
    contractAddress: "0x4007168965cBdB189A98E03C28695F900D92a11E",
  },
  {
    name: "WannaSwap",
    symbol: "WANNA",
    type: "erc20",
    Decimals: "18",
    chainFullName: "aurora",
    contractAddress: "0x7faA64Faf54750a2E3eE621166635fEAF406Ab22",
  },
  {
    name: "Avalanche",
    symbol: "AVAX",
    type: "native",
    Decimals: "18",
    chainFullName: "avalanche",
    contractAddress: "",
  },
  {
    name: "USD Coin",
    symbol: "USDC",
    type: "erc20",
    Decimals: "6",
    chainFullName: "avalanche",
    contractAddress: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
  },
  {
    name: "Tether USD",
    symbol: "USDT.e",
    type: "erc20",
    Decimals: "6",
    chainFullName: "avalanche",
    contractAddress: "0xc7198437980c041c805A1EDcbA50c1Ce5db95118",
  },
  {
    name: "Dai",
    symbol: "DAI.e",
    type: "erc20",
    Decimals: "18",
    chainFullName: "avalanche",
    contractAddress: "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70",
  },
  {
    name: "Bitcoin",
    symbol: "BTC",
    type: "native",
    Decimals: "8",
    chainFullName: "bitcoin",
    contractAddress: "",
  },
  {
    name: "Bitcoin Cash",
    symbol: "BCH",
    type: "native",
    Decimals: "8",
    chainFullName: "bitcoin_cash",
  },
  {
    name: "BNB",
    symbol: "BNB",
    type: "native",
    decimals: "18",
    chainFullName: "binance",
    contractAddress: "",
  },
  {
    name: "Dai",
    symbol: "DAI",
    type: "bep20",
    Decimals: "18",
    chainFullName: "binance",
    contractAddress: "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
  },
  {
    name: "Tether USD",
    symbol: "USDT",
    type: "bep20",
    Decimals: "18",
    chainFullName: "binance",
    contractAddress: "0x55d398326f99059fF775485246999027B3197955",
  },
  {
    name: "USD Coin",
    symbol: "USDC",
    type: "bep20",
    Decimals: "18",
    chainFullName: "binance",
    contractAddress: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
  },
  {
    name: "Celo",
    symbol: "CELO",
    type: "native",
    Decimals: "18",
    chainFullName: "celo",
    contractAddress: "",
  },
  {
    name: "Ethereum",
    symbol: "ETH",
    type: "native",
    Decimals: "18",
    chainFullName: "ethereum",
    contractAddress: "",
  },
  {
    name: "BNB",
    symbol: "BNB",
    type: "erc20",
    Decimals: "18",
    chainFullName: "ethereum",
    contractAddress: "0xB8c77482e45F1F44dE1745F52C74426C631bDD52",
  },
  {
    name: "Dai",
    symbol: "DAI",
    type: "erc20",
    Decimals: "18",
    chainFullName: "ethereum",
    contractAddress: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
  },
  {
    name: "Tether USD",
    symbol: "USDT",
    type: "erc20",
    Decimals: "6",
    chainFullName: "ethereum",
    contractAddress: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
  },
  {
    name: "USD Coin",
    symbol: "USDC",
    type: "erc20",
    Decimals: "6",
    chainFullName: "ethereum",
    contractAddress: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
  },
  {
    name: "POL",
    symbol: "POL",
    type: "erc20",
    Decimals: "18",
    chainFullName: "ethereum",
    contractAddress: "0x455e53CBB86018Ac2B8092FdCd39d8444aFFC3F6",
  },
  {
    name: "Polygon",
    symbol: "POL",
    type: "native",
    decimals: "18",
    chainFullName: "polygon",
    contractAddress: "",
  },
  {
    name: "USD Coin",
    symbol: "USDC",
    type: "erc20",
    Decimals: "6",
    chainFullName: "polygon",
    contractAddress: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
  },
  {
    name: "Dai",
    symbol: "DAI",
    type: "erc20",
    Decimals: "18",
    chainFullName: "polygon",
    contractAddress: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
  },
  {
    name: "Tether USD",
    symbol: "USDT",
    type: "erc20",
    Decimals: "6",
    chainFullName: "polygon",
    contractAddress: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
  },
  {
    name: "Ethereum Classic",
    symbol: "ETC",
    type: "native",
    decimals: "18",
    chainFullName: "ethereum_classic",
    contractAddress: "",
  },
  // Fantom Opera has migrated to Sonic and is no longer supported.
  // {
  //   name: "Fantom",
  //   symbol: "FTM",
  //   type: "native",
  //   Decimals: "18",
  //   chainFullName: "fantom",
  //   contractAddress: "",
  // },
  // {
  //   name: "USD Coin",
  //   symbol: "USDC",
  //   type: "native",
  //   Decimals: "6",
  //   chainFullName: "fantom",
  //   contractAddress: "0x04068DA6C83AFCFA0e13ba15A6696662335D5B75",
  // },
  // {
  //   name: "Dai",
  //   symbol: "DAI",
  //   type: "erc20",
  //   Decimals: "18",
  //   chainFullName: "fantom",
  //   contractAddress: "0x8D11eC38a3EB5E956B052f67Da8Bdc9bef8Abf3E",
  // },
  {
    name: "Cronos",
    symbol: "CRO",
    type: "native",
    Decimals: "18",
    chainFullName: "cronos",
    contractAddress: "",
  },
  {
    name: "IoTeX",
    symbol: "IOTX",
    type: "native",
    Decimals: "18",
    chainFullName: "iotex",
    contractAddress: "",
  },
  {
    name: "Litecoin",
    symbol: "LTC",
    type: "native",
    Decimals: "8",
    chainFullName: "litecoin",
    contractAddress: "",
  },
  // OKB is no longer supported.
  // {
  //   name: "OKT",
  //   symbol: "OKT",
  //   type: "erc20",
  //   Decimals: "",
  //   chainFullName: "okb",
  //   contractAddress: "",
  // },
  // {
  //   name: "USD Coin",
  //   symbol: "USDC",
  //   type: "native",
  //   Decimals: "18",
  //   chainFullName: "okb",
  //   contractAddress: "0xc946DAf81b08146B1C7A8Da2A851Ddf2B3EAaf85",
  // },
  // {
  //   name: "Tether USD",
  //   symbol: "USDT",
  //   type: "erc20",
  //   Decimals: "18",
  //   chainFullName: "okb",
  //   contractAddress: "0x382bB369d343125BfB2117af9c149795C6C65C50",
  // },
  {
    name: "Optimistic Ethereum",
    symbol: "OETH",
    type: "native",
    Decimals: "18",
    chainFullName: "optimism",
    contractAddress: "",
  },

  {
    name: "Optimism",
    symbol: "OP",
    type: "token",
    Decimals: "18",
    chainFullName: "optimism",
    contractAddress: "0x4200000000000000000000000000000000000042",
  },
  {
    name: "USDC.e",
    symbol: "USDC.e",
    type: "token",
    Decimals: "6",
    chainFullName: "optimism",
    contractAddress: "0x7F5c764cBc14f9669B88837ca1490cCa17c31607",
  },
  {
    name: "Tether USD",
    symbol: "USDT",
    type: "token",
    Decimals: "6",
    chainFullName: "optimism",
    contractAddress: "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58",
  },
  {
    name: "Dai",
    symbol: "DAI",
    type: "token",
    Decimals: "18",
    chainFullName: "optimism",
    contractAddress: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1",
  },
  {
    name: "Ripple",
    symbol: "XRP",
    type: "native",
    Decimals: "",
    chainFullName: "ripple",
    contractAddress: "",
  },
  {
    name: "Solana",
    symbol: "SOL",
    type: "spl",
    Decimals: "9",
    chainFullName: "solana",
    contractAddress: "",
  },
  {
    name: "Tether USD",
    symbol: "USDT",
    type: "spl",
    Decimals: "6",
    chainFullName: "solana",
    contractAddress: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
  },
  {
    name: "USD Coin",
    symbol: "USDC",
    type: "spl",
    Decimals: "6",
    chainFullName: "solana",
    contractAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    name: "Tron",
    symbol: "TRX",
    type: "native",
    Decimals: "6",
    chainFullName: "tron",
    contractAddress: "",
  },
  {
    name: "Tether",
    symbol: "USDT",
    type: "trc20",
    Decimals: "6",
    chainFullName: "tron",
    contractAddress: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
  },

  {
    name: "Ethereum",
    symbol: "ETH",
    type: "native",
    Decimals: "18",
    chainFullName: "zksync",
    contractAddress: "",
  },
  {
    name: "USD Coin Bridged",
    symbol: "USDC.e",
    type: "erc20",
    Decimals: "6",
    chainFullName: "zksync",
    contractAddress: "0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4",
  },

  {
    name: "Cosmos",
    symbol: "ATOM",
    type: "native",
    Decimals: "6",
    chainFullName: "cosmos",
    contractAddress: "",
  },
  {
    name: "Celestia",
    symbol: "TIA",
    type: "native",
    Decimals: "6",
    chainFullName: "celestia",
    contractAddress: "",
  },
  // {
  //   name: "Crypto.org Coin",
  //   symbol: "CRO",
  //   type: "crc20",
  //   Decimals: "8",
  //   chainFullName: "cryptoorg",
  //   contractAddress: "",
  // },
  // {
  //   name: "Tether USD",
  //   symbol: "USDT",
  //   type: "crc20",
  //   Decimals: "6",
  //   chainFullName: "cryptoorg",
  //   contractAddress: "0x66e428c3f67a68878562e79A0234c1F83c208770",
  // },
  {
    name: "Osmosis",
    symbol: "OSMO",
    type: "native",
    Decimals: "6",
    chainFullName: "osmosis",
    contractAddress: "",
  },
  {
    name: "Gnosis",
    symbol: "XDAI",
    type: "native",
    Decimals: "18",
    chainFullName: "gnosis",
    contractAddress: "",
  },
  {
    name: "WXDAI",
    symbol: "WXDAI",
    type: "erc20",
    Decimals: "18",
    chainFullName: "gnosis",
    contractAddress: "0xe91d153e0b41518a2ce8dd3d7944fa863463a97d",
  },
  {
    name: "USDC",
    symbol: "USDC",
    type: "erc20",
    Decimals: "6",
    chainFullName: "gnosis",
    contractAddress: "0xddafbb505ad214d7b80b1f830fccc89b60fb7a83",
  },
  {
    name: "USDT",
    symbol: "USDT",
    type: "erc20",
    Decimals: "6",
    chainFullName: "gnosis",
    contractAddress: "0x4ecaba5870353805a9f068101a40e0f32ed605c6",
  },
  {
    name: "WETH",
    symbol: "WETH",
    type: "erc20",
    Decimals: "18",
    chainFullName: "gnosis",
    contractAddress: "0x6a023ccd1ff6f2045c3309768ead9e68f978f6e1",
  },
  {
    name: "Ethereum",
    symbol: "ETH",
    type: "native",
    Decimals: "18",
    chainFullName: "linea",
    contractAddress: "",
  },
  {
    name: "Ronin",
    symbol: "RON",
    type: "native",
    Decimals: "18",
    chainFullName: "ronin",
    contractAddress: "",
  },
  {
    name: "Aptos",
    symbol: "APT",
    type: "native",
    Decimals: "8",
    chainFullName: "aptos",
    contractAddress: "",
  },
  {
    name: "Sui",
    symbol: "SUI",
    type: "native",
    Decimals: "9",
    chainFullName: "sui",
    contractAddress: "",
  },
  {
    name: "USDC",
    symbol: "USDC",
    type: "token",
    Decimals: "6",
    chainFullName: "sui",
    contractAddress:
      "0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC",
  },
  {
    name: "Dogecoin",
    symbol: "DOGE",
    type: "native",
    Decimals: "8",
    chainFullName: "dogecoin",
    contractAddress: "",
  },
];

export const isHiddenInDevelopmentAsset = (asset) =>
  !RUNTIME_DEV &&
  hiddenInDevelopmentChainNames.has(
    String(getAssetChainFullName(asset) || "")
      .trim()
      .toLowerCase(),
  );

export const isRemovedAsset = (asset) =>
  removedAssetKeys.has(getAssetKey(asset));

export const initialAdditionalCryptos = configuredInitialAdditionalCryptos
  .filter(
    (asset) => !isHiddenInDevelopmentAsset(asset) && !isRemovedAsset(asset),
  )
  .map(normalizeAssetConfig);
