/*
 * This file is part of the open source LUKKEY project.
 * Licensed under the MIT License. See LICENSE for details.
 * © Copyright LUKKEY AG
 */
export const initialAdditionalCryptos = [
  {
    name: "Arbitrum",
    shortName: "ARB",
    queryChainName: "arbitrum",
    queryChainShortName: "ARB",
    coin_type: "erc20",
    fee: "0.0",
    Decimals: "18",
    contractAddress: "0x912CE59144191C1204E64559FE8253a0e49E6548",
  },
  {
    name: "Ethereum",
    shortName: "ARETH",
    queryChainName: "arbitrum",
    queryChainShortName: "ARB",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },
  {
    name: "Dai",
    shortName: "DAI",
    queryChainName: "arbitrum",
    queryChainShortName: "ARB",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1",
    Decimals: "18",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    queryChainShortName: "ARB",
    queryChainName: "arbitrum",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9",
    Decimals: "6",
  },
  {
    name: "Bridged USDC",
    shortName: "USDC.e",
    queryChainShortName: "ARB",
    queryChainName: "arbitrum",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8",
    Decimals: "6",
  },
  {
    name: "Aurora",
    shortName: "AURORA",
    queryChainShortName: "AURORA",
    queryChainName: "aurora",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "",
  },
  {
    name: "Avalanche",
    shortName: "AVAX",
    queryChainShortName: "AVAX",
    queryChainName: "avalanche",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    queryChainShortName: "AVAX",
    queryChainName: "avalanche",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
    Decimals: "6",
  },
  {
    name: "Tether USD",
    shortName: "USDT.e",
    queryChainShortName: "AVAX",
    queryChainName: "avalanche",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xc7198437980c041c805A1EDcbA50c1Ce5db95118",
    Decimals: "6",
  },
  {
    name: "Dai",
    shortName: "DAI.e",
    queryChainShortName: "AVAX",
    queryChainName: "avalanche",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70",
    Decimals: "18",
  },
  {
    name: "Bitcoin",
    shortName: "BTC",
    queryChainShortName: "BTC",
    queryChainName: "bitcoin",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "8",
  },
  {
    name: "Bitcoin Cash",
    shortName: "BCH",
    queryChainShortName: "BCH",
    queryChainName: "bitcoin_cash",
    coin_type: "native",
    fee: "0.0",
    Decimals: "8",
  },
  {
    name: "BNB",
    shortName: "BNB",
    queryChainShortName: "BNB",
    queryChainName: "binance",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    decimals: "18",
  },
  {
    name: "Dai",
    shortName: "DAI",
    queryChainShortName: "BNB",
    queryChainName: "binance",
    coin_type: "bep20",
    fee: "0.0",
    contractAddress: "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
    Decimals: "18",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    queryChainShortName: "BNB",
    queryChainName: "binance",
    coin_type: "bep20",
    fee: "0.0",
    contractAddress: "0x55d398326f99059fF775485246999027B3197955",
    Decimals: "18",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    queryChainShortName: "BNB",
    queryChainName: "binance",
    coin_type: "bep20",
    fee: "0.0",
    contractAddress: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
    Decimals: "18",
  },
  {
    name: "Celo",
    shortName: "CELO",
    queryChainShortName: "CELO",
    queryChainName: "celo",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },
  {
    name: "Ethereum",
    shortName: "ETH",
    queryChainShortName: "ETH",
    queryChainName: "ethereum",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },
  {
    name: "BNB",
    shortName: "BNB",
    queryChainShortName: "ETH",
    queryChainName: "ethereum",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xB8c77482e45F1F44dE1745F52C74426C631bDD52",
    Decimals: "18",
  },
  {
    name: "Dai",
    shortName: "DAI",
    queryChainShortName: "ETH",
    queryChainName: "ethereum",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
    Decimals: "18",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    queryChainShortName: "ETH",
    queryChainName: "ethereum",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    Decimals: "6",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    queryChainShortName: "ETH",
    queryChainName: "ethereum",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    Decimals: "6",
  },
  /*   {
    name: "Polygon",
    shortName: "POL",
    queryChainShortName: "ETH",
    queryChainName: "ethereum",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0",
    Decimals: "18",}, */
  {
    name: "Polygon",
    shortName: "POL",
    queryChainShortName: "POL",
    queryChainName: "polygon",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    decimals: "18",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    queryChainShortName: "POL",
    queryChainName: "polygon",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
    Decimals: "6",
  },
  {
    name: "Dai",
    shortName: "DAI",
    queryChainShortName: "POL",
    queryChainName: "polygon",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
    Decimals: "18",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    queryChainShortName: "POL",
    queryChainName: "polygon",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
    Decimals: "6",
  },
  {
    name: "Ethereum Classic",
    shortName: "ETC",
    queryChainShortName: "ETC",
    queryChainName: "ethereum_classic",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    decimals: "18",
  },
  {
    name: "Fantom",
    shortName: "FTM",
    queryChainShortName: "FTM",
    queryChainName: "fantom",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    queryChainShortName: "FTM",
    queryChainName: "fantom",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "0x04068DA6C83AFCFA0e13ba15A6696662335D5B75",
    Decimals: "6",
  },
  {
    name: "Dai",
    shortName: "DAI",
    queryChainShortName: "FTM",
    queryChainName: "fantom",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0x8D11eC38a3EB5E956B052f67Da8Bdc9bef8Abf3E",
    Decimals: "18",
  },
  {
    name: "Cronos",
    shortName: "CRO",
    queryChainShortName: "CRO",
    queryChainName: "cronos",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },
  {
    name: "IoTeX",
    shortName: "IOTX",
    queryChainShortName: "IOTX",
    queryChainName: "iotex",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },
  {
    name: "Litecoin",
    shortName: "LTC",
    queryChainShortName: "LTC",
    queryChainName: "litecoin",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "8",
  },
  {
    name: "OKT",
    shortName: "OKT",
    queryChainShortName: "OKT",
    queryChainName: "okb",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "",
    Decimals: "",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    queryChainShortName: "OKT",
    queryChainName: "okb",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "0xc946DAf81b08146B1C7A8Da2A851Ddf2B3EAaf85",
    Decimals: "18",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    queryChainShortName: "OKT",
    queryChainName: "okb",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "0x382bB369d343125BfB2117af9c149795C6C65C50",
    Decimals: "18",
  },
  {
    name: "Optimistic Ethereum",
    shortName: "OETH",
    queryChainShortName: "OP",
    queryChainName: "optimism",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },

  {
    name: "Optimism",
    shortName: "OP",
    queryChainShortName: "OP",
    queryChainName: "optimism",
    coin_type: "token",
    fee: "0.0",
    contractAddress: "0x4200000000000000000000000000000000000042",
    Decimals: "18",
  },
  {
    name: "USDC.e",
    shortName: "USDC.e",
    queryChainShortName: "OP",
    queryChainName: "optimism",
    coin_type: "token",
    fee: "0.0",
    contractAddress: "0x7F5c764cBc14f9669B88837ca1490cCa17c31607",
    Decimals: "6",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    queryChainShortName: "OP",
    queryChainName: "optimism",
    coin_type: "token",
    fee: "0.0",
    contractAddress: "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58",
    Decimals: "6",
  },
  {
    name: "Dai",
    shortName: "DAI",
    queryChainShortName: "OP",
    queryChainName: "optimism",
    coin_type: "token",
    fee: "0.0",
    contractAddress: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1",
    Decimals: "18",
  },
  {
    name: "Ripple",
    shortName: "XRP",
    queryChainShortName: "XRP",
    queryChainName: "ripple",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "",
  },
  {
    name: "Solana",
    shortName: "SOL",
    queryChainShortName: "SOL",
    queryChainName: "solana",
    coin_type: "spl",
    fee: "0.0",
    contractAddress: "",
    Decimals: "9",
  },
  {
    name: "Tether USD",
    shortName: "USDT",
    queryChainShortName: "SOL",
    queryChainName: "solana",
    coin_type: "spl",
    fee: "0.0",
    contractAddress: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    Decimals: "6",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    queryChainShortName: "SOL",
    queryChainName: "solana",
    coin_type: "spl",
    fee: "0.0",
    contractAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    Decimals: "6",
  },
  {
    name: "Tron",
    shortName: "TRX",
    queryChainShortName: "TRX",
    queryChainName: "tron",
    coin_type: "trc20",
    fee: "0.0",
    contractAddress: "",
    Decimals: "6",
  },
  {
    name: "USD Coin",
    shortName: "USDC",
    queryChainShortName: "TRX",
    queryChainName: "tron",
    coin_type: "trc20",
    fee: "0.0",
    contractAddress: "TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8",
    Decimals: "6",
  },
  {
    name: "Tether",
    shortName: "USDT",
    queryChainShortName: "TRX",
    queryChainName: "tron",
    coin_type: "trc20",
    fee: "0.0",
    contractAddress: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
    Decimals: "6",
  },

  {
    name: "Ethereum",
    shortName: "ETH",
    queryChainShortName: "ZKSYNC",
    queryChainName: "zksync",
    coin_type: "erc20",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },
  {
    name: "zkSync Era",
    shortName: "ZKSYNC",
    queryChainShortName: "ZKSYNC",
    queryChainName: "zksync",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "",
  },

  {
    name: "Cosmos",
    shortName: "ATOM",
    queryChainShortName: "ATOM",
    queryChainName: "cosmos",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "6",
  },
  /*   {
    name: "Celestia",
    shortName: "CEL",
    queryChainShortName: "CEL",
    queryChainName: "celestia",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "",}, */
  /*   {
    name: "Crypto.org Coin",
    shortName: "CRO",
    queryChainShortName: "CRO",
    queryChainName: "cryptoorg",
    coin_type: "crc20",
    fee: "0.0",
    contractAddress: "",
    Decimals: "8",},
  {
    name: "Tether USD",
    shortName: "USDT",
    queryChainShortName: "CRO",
    queryChainName: "cryptoorg",
    coin_type: "crc20",
    fee: "0.0",
    contractAddress: "0x66e428c3f67a68878562e79A0234c1F83c208770",
    Decimals: "6",}, */
  /* Juno is currently semi-dead; hide it from the default asset list for now.
  {
    name: "Juno",
    shortName: "JUNO",
    queryChainShortName: "JUNO",
    queryChainName: "juno",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "6",
  }, */
  {
    name: "Osmosis",
    shortName: "OSMO",
    queryChainShortName: "OSMO",
    queryChainName: "osmosis",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "6",
  },
  /*   {
    name: "Gnosis",
    shortName: "GNO",
    queryChainShortName: "GNO",
    queryChainName: "gnosis",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",}, */
  /*   {
    name: "Huobi Token",
    shortName: "HTX",
    queryChainShortName: "HTX",
    queryChainName: "cronos",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "",}, */

  /*   {
    name: "Linea",
    shortName: "LINEA",
    queryChainShortName: "LINEA",
    queryChainName: "linea",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",}, */
  {
    name: "Ronin",
    shortName: "RON",
    queryChainShortName: "RON",
    queryChainName: "ronin",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "18",
  },
  {
    name: "Aptos",
    shortName: "APT",
    queryChainShortName: "APT",
    queryChainName: "aptos",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "8",
  },
  {
    name: "Sui",
    shortName: "SUI",
    queryChainShortName: "SUI",
    queryChainName: "sui",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "9",
  },
  {
    name: "USDC",
    shortName: "USDC",
    queryChainShortName: "SUI",
    queryChainName: "sui",
    coin_type: "token",
    fee: "0.0",
    contractAddress:
      "0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7",
    Decimals: "6",
  },

  {
    name: "Dogecoin",
    shortName: "DOGE",
    queryChainName: "dogecoin",
    coin_type: "native",
    fee: "0.0",
    contractAddress: "",
    Decimals: "8",
  },
];
