/*
 * This file is part of the open source LUKKEY project.
 * Licensed under the MIT License. See LICENSE for details.
 * © Copyright LUKKEY AG
 */
export const iconToCardImageEntries = [
  [
    require("../assets/icon/ARBIcon.webp"),
    require("../assets/CardBg/Card15.webp"),
  ],
  [
    require("../assets/icon/ETHIcon.webp"),
    require("../assets/CardBg/Card35.webp"),
  ],
  [
    require("../assets/icon/DAIIcon.webp"),
    require("../assets/CardBg/Card55.webp"),
  ],
  [
    require("../assets/icon/USDTIcon.webp"),
    require("../assets/CardBg/Card101.webp"),
  ],
  [
    require("../assets/icon/USDCIcon.webp"),
    require("../assets/CardBg/Card107.webp"),
  ],
  [
    require("../assets/icon/AURORAIcon.webp"),
    require("../assets/CardBg/Card10.webp"),
  ],
  [
    require("../assets/icon/AVAXIcon.webp"),
    require("../assets/CardBg/Card21.webp"),
  ],
  [
    require("../assets/icon/BTCIcon.webp"),
    require("../assets/CardBg/Card22.webp"),
  ],
  [
    require("../assets/icon/BCHIcon.webp"),
    require("../assets/CardBg/Card8.webp"),
  ],
  [
    require("../assets/icon/BNBIcon.webp"),
    require("../assets/CardBg/Card41.webp"),
  ],
  [
    require("../assets/icon/CELOIcon.webp"),
    require("../assets/CardBg/Card111.webp"),
  ],
  [
    require("../assets/icon/PolygonIcon.webp"),
    require("../assets/CardBg/Card18.webp"),
  ],
  [
    require("../assets/icon/ETCIcon.webp"),
    require("../assets/CardBg/Card62.webp"),
  ],
  [
    require("../assets/icon/FTMIcon.webp"),
    require("../assets/CardBg/Card45.webp"),
  ],
  [
    require("../assets/icon/CROIcon.webp"),
    require("../assets/CardBg/Card56.webp"),
  ],
  [
    require("../assets/icon/IOTXIcon.webp"),
    require("../assets/CardBg/Card78.webp"),
  ],
  [
    require("../assets/icon/LTCIcon.webp"),
    require("../assets/CardBg/Card100.webp"),
  ],
  [
    require("../assets/icon/OKTIcon.webp"),
    require("../assets/CardBg/Card106.webp"),
  ],
  [
    require("../assets/icon/OPIcon.webp"),
    require("../assets/CardBg/Card81.webp"),
  ],
  [
    require("../assets/icon/XRPIcon.webp"),
    require("../assets/CardBg/Card84.webp"),
  ],
  [
    require("../assets/icon/SOLIcon.webp"),
    require("../assets/CardBg/Card2.webp"),
  ],
  [
    require("../assets/icon/TRXIcon.webp"),
    require("../assets/CardBg/Card97.webp"),
  ],
  [
    require("../assets/icon/ZKSIcon.webp"),
    require("../assets/CardBg/Card94.webp"),
  ],
  [
    require("../assets/icon/ATOMIcon.webp"),
    require("../assets/CardBg/Card38.webp"),
  ],
  [
    require("../assets/icon/JUNOIcon.webp"),
    require("../assets/CardBg/Card91.webp"),
  ],
  [
    require("../assets/icon/OSMOIcon.webp"),
    require("../assets/CardBg/Card104.webp"),
  ],
  [
    require("../assets/icon/RONIcon.webp"),
    require("../assets/CardBg/Card83.webp"),
  ],
  [
    require("../assets/icon/APTIcon.webp"),
    require("../assets/CardBg/Card14.webp"),
  ],
  [
    require("../assets/icon/SUIIcon.webp"),
    require("../assets/CardBg/Card108.webp"),
  ],
  [
    require("../assets/icon/DOGEIcon.webp"),
    require("../assets/CardBg/Card113.webp"),
  ],
];
